# Generated by Django 2.0.1 on 2018-01-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Atype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Виды наркоза',
                'verbose_name': 'вид наркоза',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('even_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 1')),
                ('odd_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 2')),
            ],
            options={
                'verbose_name_plural': 'Корпусы',
                'verbose_name': 'корпус',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Отделения',
                'verbose_name': 'отделение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('enable', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name_plural': 'Работники',
                'verbose_name': 'работник',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Показывать')),
                ('template', models.BooleanField(default=False, verbose_name='Создавать каждый раз')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Расписания',
                'verbose_name': 'расписание',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VacationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Отпуска',
                'verbose_name': 'отпуск',
                'ordering': ['employee__name'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Place')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Палаты',
                'verbose_name': 'палата',
                'ordering': ['name'],
            },
            bases=('main.place',),
        ),
        migrations.CreateModel(
            name='ChamberLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Line')),
                ('chamber', models.ManyToManyField(blank=True, limit_choices_to={'enable': True}, to='main.Chamber', verbose_name='Палаты')),
            ],
            options={
                'verbose_name_plural': 'Расписание для палат',
                'verbose_name': 'назначение для палаты',
                'ordering': ['chamber__name'],
            },
            bases=('main.line',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Employee')),
            ],
            options={
                'verbose_name_plural': 'Врачи',
                'verbose_name': 'врач',
            },
            bases=('main.employee',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Employee')),
            ],
            options={
                'verbose_name_plural': 'Медсестры',
                'verbose_name': 'медсестра',
            },
            bases=('main.employee',),
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Employee')),
            ],
            options={
                'verbose_name_plural': 'Ординаторы',
                'verbose_name': 'ординатор',
            },
            bases=('main.employee',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Place')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('number', models.CharField(blank=True, max_length=9, verbose_name='Номер')),
                ('free_dept', models.BooleanField(default=False, verbose_name='Для разных отделений')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Building', verbose_name='Корпус')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name_plural': 'Операционные',
                'verbose_name': 'операционная',
                'ordering': ['building__name', '-floor', 'number'],
            },
            bases=('main.place',),
        ),
        migrations.CreateModel(
            name='RoomLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Line')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='Комментарий')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('oair', models.IntegerField(blank=True, null=True, verbose_name='в ОАиР')),
                ('dept', models.ManyToManyField(to='main.Department', verbose_name='Отделения')),
            ],
            options={
                'verbose_name_plural': 'Расписание операционных',
                'verbose_name': 'назначение операционной',
                'ordering': ['room__building__name', '-room__floor', 'room__number'],
            },
            bases=('main.line',),
        ),
        migrations.AddField(
            model_name='vacationline',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Employee', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='vacationline',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Table'),
        ),
        migrations.AddField(
            model_name='line',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Table'),
        ),
        migrations.AddField(
            model_name='aspec',
            name='atype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Atype'),
        ),
        migrations.AddField(
            model_name='roomline',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linelink', to='main.Line', verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='roomline',
            name='nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Nurse', verbose_name='Медсестра'),
        ),
        migrations.AddField(
            model_name='roomline',
            name='room',
            field=models.ForeignKey(limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Room', verbose_name='Операционная'),
        ),
        migrations.AddField(
            model_name='line',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='line',
            name='resident',
            field=models.ForeignKey(blank=True, limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Resident', verbose_name='Ординатор'),
        ),
        migrations.AddField(
            model_name='aspec',
            name='room_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RoomLine'),
        ),
    ]
