# Generated by Django 2.0.1 on 2018-02-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='aspec',
            name='atype',
        ),
        migrations.RemoveField(
            model_name='aspec',
            name='room_line',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'анестезиолог', 'verbose_name_plural': 'Анестезиологи'},
        ),
        migrations.AlterField(
            model_name='building',
            name='even_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 2'),
        ),
        migrations.AlterField(
            model_name='building',
            name='odd_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 1'),
        ),
        migrations.AlterField(
            model_name='line',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'enable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Doctor', verbose_name='Анестезиолог'),
        ),
        migrations.AlterField(
            model_name='roomline',
            name='begin_time',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='roomline',
            name='dept',
            field=models.ManyToManyField(blank=True, to='main.Department', verbose_name='Отделения'),
        ),
        migrations.DeleteModel(
            name='Aspec',
        ),
        migrations.DeleteModel(
            name='Atype',
        ),
        migrations.AddField(
            model_name='columnvalue',
            name='room_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RoomLine'),
        ),
    ]
